In [1]:
import mysql.connector
import pandas as pd
class Barang:
    
    def __init__(self, id_barang, nama_barang, kuantitas, harga_beli, harga_jual):        
        self.id_barang = id_barang
        self.nama_barang = nama_barang
        self.kuantitas = kuantitas
        self.harga_beli = harga_beli
        self.harga_jual = harga_jual
        
   
    def tampilkan_data_barang(self): 
        print("============Data Barang============")
        print("ID Barang:", self.id_barang)
        print("Nama Barang:", self.nama_barang)
        print("Kuantitas:", self.kuantitas)
        print("Harga Beli:", self.harga_beli)
        print("Harga Jual:", self.harga_jual)

class Pegawai:
    def __init__(self, id_pegawai, nama_pegawai, no_hp):        
        self.id_pegawai = id_pegawai
        self.nama_pegawai = nama_pegawai
        self.no_hp = no_hp
    
    def tampilkan_data_pegawai(self): 
        print("============Data Pegawai============")
        print("ID Pegawai :", self.id_pegawai)
        print("Nama Pegawai :", self.nama_pegawai)
        print("No HP :", self.no_hp)        
        
class Penjualan(Barang, Pegawai):
    def __init__(self, id_penjualan, barang, pegawai, tanggal_penjualan, kuantitas_jual):
        Barang.__init__(self, barang.id_barang, barang.nama_barang, barang.kuantitas, barang.harga_beli, barang.harga_jual)
        Pegawai.__init__(self, pegawai.id_pegawai, pegawai.nama_pegawai, pegawai.no_hp)
        
        self.id_penjualan = id_penjualan
        self.tanggal_penjualan = tanggal_penjualan
        self.kuantitas_jual = kuantitas_jual  
        self.harga_jual = barang.harga_jual
        self.jumlah = kuantitas_jual*barang.harga_jual
        
        print("==========Penjualan==========")
        print("waktu : ", self.tanggal_penjualan)
        print("Kuantitas jual : ", self.kuantitas_jual)
        print("Harga jual : ", self.harga_jual)
        print("Jumlah : ", self.jumlah)

        super().tampilkan_data_barang()
        super().tampilkan_data_pegawai()
        
class Pembelian(Barang, Pegawai):
    def __init__(self, id_pembelian, barang, pegawai, tanggal_pembelian):       
        Barang.__init__(self, barang.id_barang, barang.nama_barang, barang.kuantitas, barang.harga_beli, barang.harga_jual)
        Pegawai.__init__(self, pegawai.id_pegawai, pegawai.nama_pegawai, pegawai.no_hp)
        
        self.id_pembelian = id_pembelian
        self.tanggal_pembelian = tanggal_pembelian
        self.kuantitas_beli = barang.kuantitas
        self.harga_beli = barang.harga_beli
        self.jumlah = self.kuantitas_beli*barang.harga_beli

        
        print("==========Pembelian==========")
        print("Tanggal Pembelian : ",self.tanggal_pembelian)
        print("Kuantitas Beli : ",self.kuantitas_beli)
        
        super().tampilkan_data_barang()
        super().tampilkan_data_pegawai()

In [9]:
import mysql.connector
import pandas as pd

class Penjualan_CRUD:

    def __init__(self, penjualan):                               
        self.id_penjualan = penjualan.id_penjualan
        self.id_pegawai = penjualan.id_pegawai
        self.id_barang = penjualan.id_barang 
        self.tanggal_penjualan = penjualan.tanggal_penjualan
        self.kuantitas_jual = penjualan.kuantitas_jual
        self.harga_jual = penjualan.harga_jual
        self.jumlah = penjualan.jumlah
        
        conn = None

    @staticmethod
    def get_koneksi_db():
        conn = mysql.connector.connect(host="localhost" ,
                                            user="root",
                                            password="",
                                            database="warung")
        if conn.is_connected():
            print("Berhasil terhubung ke database")
        
        return conn

    def insert_data(self):
        koneksi_db = Penjualan_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "INSERT INTO penjualan (id_pegawai, id_barang, kuantitas, harga_satuan, jumlah) VALUES (%s, %s, %s, %s, %s)"
        val = (self.id_pegawai, self.id_barang, self.kuantitas_jual, self.harga_jual, self.jumlah)
        
        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data ditambahkan".format(cursor.rowcount))
        Penjualan_CRUD.tampilkan_dataframe()
        
    def update_data(self):
        koneksi_db = Penjualan_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "UPDATE penjualan set id_pegawai=%s, id_barang=%s, waktu=%s, kuantitas=%s, harga_satuan=%s, jumlah=%s WHERE id_penjualan=%s"
        val = (self.id_pegawai, self.id_barang, self.waktu, self.kuantitas_jual, self.harga_jual, self.jumlah, self.id_penjualan)

        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data diupdate".format(cursor.rowcount))
        Penjualan_CRUD.tampilkan_dataframe()

    
    def delete_data(self):
        koneksi_db = Penjualan_CRUD.get_koneksi_db()
        cursor = koneksi_db.cursor()
        
        sql = "DELETE FROM penjualan WHERE id_penjualan=%s"
        val = (self.id_pembelian, )
        cursor.execute(sql, val)

        koneksi_db.commit()

        print("{} data dihapus".format(cursor.rowcount))
        Penjualan_CRUD.tampilkan_dataframe()
            
    @staticmethod
    def tampilkan_dataframe():
        koneksi_db = Penjualan_CRUD.get_koneksi_db()
        
        #ql = "SELECT * FROM pembelian"
        sql = "SELECT penjualan.*, barang.nama_barang, pegawai.nama_pegawai FROM `penjualan` LEFT JOIN barang ON penjualan.id_barang = barang.id_barang LEFT JOIN pegawai ON penjualan.id_pegawai = pegawai.id_pegawai"
        
        df = pd.read_sql(sql, con=koneksi_db)
        
        display(df)

In [ ]:
pegawai = Pegawai_CRUD.tampilkan_satu_data(1)

barang = Barang_CRUD.tampilkan_satu_data(21)

penjualan = Penjualan("", barang, pegawai, "4 Maret 2021", 10)

Penjualan_CRUD(penjualan).insert_data()